# Generated by Django 4.0.4 on 2022-05-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='producs',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='useR',
            new_name='user',
        ),
    ]
